Python/WebBasics/exam/exam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("fruitipedia.urls")),
]

Python/WebBasics/exam/fruitipedia/urls.py
from django.urls import path, include
from . import views

app_name = "fruitipedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path(
        "profile/",
        include(
            [
                path("create/", views.profile_create, name="profile_create"),
                path(
                    "details/", views.profile_details, name="profile_details"
                ),
                path("edit/", views.profile_edit, name="profile_edit"),
                path("delete/", views.profile_delete, name="profile_delete"),
            ]
        ),
    ),
    path("create/", views.fruit_create, name="fruit_create"),
    path("<int:fruit_id>/details", views.fruit_details, name="fruit_details"),
    path("<int:fruit_id>/edit", views.fruit_edit, name="fruit_edit"),
    path("<int:fruit_id>/delete", views.fruit_delete, name="fruit_delete"),
]

Python/WebBasics/exam/fruitipedia/models.py
from django.db import models
from django.core.validators import RegexValidator

start_with_letter = RegexValidator(
    "^[A-Za-z]", "Your name must start with a letter!"
)
only_letters = RegexValidator(
    "^[A-Za-z]+$", "Fruit name should contain only letters!"
)
min_eight_letters = RegexValidator(
    "^.{8,}$", "Field should contain at least 8 symbols"
)
min_two_letters = RegexValidator(
    "^.{2,}$", "Field should contain at least 2 symbols"
)
min_one_letter = RegexValidator(
    "^.{1,}$", "Field should contain at least 1 symbol"
)


class ProfileModel(models.Model):
    first_name = models.CharField(
        verbose_name="First Name",
        max_length=25,
        validators=[start_with_letter, min_two_letters],
    )
    last_name = models.CharField(
        verbose_name="Last Name",
        max_length=35,
        validators=[start_with_letter, min_one_letter],
    )
    email = models.EmailField(verbose_name="Email", max_length=40)
    password = models.CharField(
        verbose_name="Password", max_length=20, validators=[min_eight_letters]
    )
    image_url = models.URLField(verbose_name="Image URL", blank=True)
    age = models.IntegerField(verbose_name="Age", default=18, blank=True)


class FruitModel(models.Model):
    name = models.CharField(
        verbose_name="Name",
        max_length=30,
        validators=[only_letters, min_two_letters],
    )
    image_url = models.URLField(verbose_name="Image URL")
    description = models.TextField(verbose_name="Description")
    nutrition = models.TextField(verbose_name="Nutrition", blank=True)

Python/WebBasics/exam/fruitipedia/forms.py
from .models import ProfileModel, FruitModel
from django import forms


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__set_attributes()

    def __set_attributes(self):
        for field in self.fields.values():
            field.label = False

        self.fields["first_name"].widget.attrs["placeholder"] = "First Name"
        self.fields["last_name"].widget.attrs["placeholder"] = "Last Name"
        self.fields["email"].widget.attrs["placeholder"] = "Email"
        self.fields["password"].widget.attrs["placeholder"] = "Password"

    class Meta:
        model = ProfileModel
        fields = ["first_name", "last_name", "email", "password"]


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = ProfileModel
        fields = ["first_name", "last_name", "image_url", "age"]


class FruitForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__set_attributes()

    def __set_attributes(self):
        for field in self.fields.values():
            field.label = False

        self.fields["name"].widget.attrs["placeholder"] = "Fruit Name"
        self.fields["image_url"].widget.attrs[
            "placeholder"
        ] = "Fruit Image URL"
        self.fields["description"].widget.attrs[
            "placeholder"
        ] = "Fruit Description"
        self.fields["nutrition"].widget.attrs["placeholder"] = "Nutrition Info"
        self.fields["nutrition"].required = False

    class Meta:
        model = FruitModel
        fields = "__all__"


class FruitEditForm(forms.ModelForm):
    class Meta:
        model = FruitModel
        fields = "__all__"


class DeleteFruitForm(FruitForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__set_attributes()

    def __set_attributes(self):
        for field in self.fields.values():
            field.widget.attrs["disabled"] = "disabled"
            field.widget.attrs["readonly"] = "readonly"

Python/WebBasics/exam/fruitipedia/views.py
from django.shortcuts import render
from . import forms, models
from django.shortcuts import redirect


def index(request):
    profile = models.ProfileModel.objects.first()
    return render(request, "index.html", {"profile": profile})


def dashboard(request):
    fruits = models.FruitModel.objects.all()
    profile = models.ProfileModel.objects.first()
    return render(
        request, "dashboard.html", {"profile": profile, "fruits": fruits}
    )


def profile_create(request):
    if request.method == "POST":
        form = forms.ProfileForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("fruitipedia:dashboard")
        else:
            return render(request, "create-profile.html", {"form": form})
    else:
        form = forms.ProfileForm()
        return render(request, "create-profile.html", {"form": form})


def profile_details(request):
    profile = models.ProfileModel.objects.first()
    fruits = models.FruitModel.objects.all()
    return render(
        request, "details-profile.html", {"profile": profile, "fruits": fruits}
    )


def profile_edit(request):
    profile = models.ProfileModel.objects.first()

    if request.method == "POST":
        form = forms.ProfileEditForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect("fruitipedia:profile_details")
        else:
            return render(
                request,
                "edit-profile.html",
                {"profile": profile, "form": form},
            )

    else:
        form = forms.ProfileEditForm(initial=profile.__dict__)

        return render(
            request, "edit-profile.html", {"profile": profile, "form": form}
        )


def profile_delete(request):
    profile = models.ProfileModel.objects.first()
    fruits = models.FruitModel.objects.all()

    if request.method == "POST":
        profile.delete()
        fruits.delete()
        return redirect("fruitipedia:index")

    else:
        return render(request, "delete-profile.html", {"profile": profile})


def fruit_create(request):
    profile = models.ProfileModel.objects.first()
    if request.method == "POST":
        form = forms.FruitForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("fruitipedia:dashboard")
        else:
            return render(
                request,
                "create-fruit.html",
                {"profile": profile, "form": form},
            )
    else:
        form = forms.FruitForm()
        return render(
            request, "create-fruit.html", {"profile": profile, "form": form}
        )


def fruit_details(request, fruit_id):
    profile = models.ProfileModel.objects.first()
    fruit = models.FruitModel.objects.get(id=fruit_id)
    return render(
        request, "details-fruit.html", {"profile": profile, "fruit": fruit}
    )


def fruit_edit(request, fruit_id):
    fruit = models.FruitModel.objects.get(id=fruit_id)
    profile = models.ProfileModel.objects.first()
    if request.method == "POST":
        form = forms.FruitEditForm(request.POST, instance=fruit)
        if form.is_valid():
            form.save()
            return redirect("fruitipedia:dashboard")
        else:
            return render(
                request, "edit-fruit.html", {"profile": profile, "form": form}
            )

    else:
        form = forms.FruitEditForm(initial=fruit.__dict__)
        return render(
            request, "edit-fruit.html", {"profile": profile, "form": form}
        )


def fruit_delete(request, fruit_id):
    fruit = models.FruitModel.objects.get(id=fruit_id)

    if request.method == "GET":
        form = forms.DeleteFruitForm(initial=fruit.__dict__)
        profile = models.ProfileModel.objects.first()
        return render(
            request, "delete-fruit.html", {"profile": profile, "form": form}
        )
    else:
        fruit.delete()
        return redirect("fruitipedia:dashboard")

Python/WebBasics/exam/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <title>Fruitipedia</title>

    <link rel="stylesheet" type="text/css" href="{% static 'styles/styles.css' %}">
  </head>
  <body>
    <div id="wrapper">
      {% include "core/header.html" with static=static %}

      <main>
          {% block content %} {% endblock %} 
      </main>

      {% include "core/footer.html" with static=static %}
    </div>
  </body>
</html>

Python/WebBasics/exam/templates/core/footer.html
{% load static %} 

{% block content %}

<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
  </footer>

{% endblock %}

Python/WebBasics/exam/templates/core/header.html
{% load static %} 

{% block content %}

<header>
    <a id="logo" href="{% url 'fruitipedia:index' %}">
        <img id="logo-img" src="/static/images/logo.png" alt="logo"/>
    </a>

    <nav>
        {% if profile %}
            <div class="user">
                <a href="{% url 'fruitipedia:dashboard' %}">Dashboard</a>
                <a href="{% url 'fruitipedia:fruit_create' %}">Add Fruit</a>
                <a href="{% url 'fruitipedia:profile_details' %}">Profile</a>
            </div>
        {% else %}
            <div class="guest">
                <a href="{% url 'fruitipedia:profile_create' %}">Create Profile</a>
            </div>
        {% endif %}
    </nav>
</header>

{% endblock %}

Python/WebBasics/exam/templates/create-fruit.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <section id="create">
        <div class="form">
            <h2>Add Fruit</h2>
            <form class="create-form" method="POST">
                {{ form }}
                {% csrf_token %}
                <button type="submit">Add Fruit</button>
            </form>
        </div>
    </section>

{% endblock %}

Python/WebBasics/exam/templates/create-profile.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <section id="register">
        <div class="form">
            <h2>Create Profile</h2>
            <form class="register-form" method="POST">
                {{ form }}
                <button type="submit">Create</button>
                {% csrf_token %}
            </form>
        </div>
    </section>
{% endblock %}

Python/WebBasics/exam/templates/dashboard.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <h2>Fruits</h2>
        {% if fruits %}
            <section id="dashboard">
                {% for fruit in fruits %}
                    <div class="fruit">
                        <img src="{{ fruit.image_url }}" alt="{{ fruit.name }}"/>
                        <h3 class="title">{{ fruit.name }}</h3>
                        <p>{{fruit.description|truncatechars:50}}</p>
                        <a class="details-btn" href="{% url 'fruitipedia:fruit_details' fruit.id %}">More Info</a>
                    </div>
                {% endfor %}
            </section>
        {% else %}
            <h2>No fruit info yet.</h2>
        {% endif %}
{% endblock %}

Python/WebBasics/exam/templates/delete-fruit.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <section id="edit">
        <div class="form">
            <h2>Delete Fruit</h2>
            <form class="edit-form" method="POST">
                {{ form }}
                {% csrf_token %}
                <button type="submit">Delete</button>
            </form>
        </div>
    </section>
{% endblock %}

Python/WebBasics/exam/templates/delete-profile.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <section id="edit">
        <div class="form">
            <h1>Are you sure you want to delete your profile?</h1>
            <form id='delete' class="register-form" method="POST">
                <button type="submit">Yes</button>
                {% csrf_token %}
            </form>
        </div>
    </section>
{% endblock %}

Python/WebBasics/exam/templates/details-fruit.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <section id="details">
        <div id="details-wrapper">
            <img id="details-img" src="{{ fruit.image_url }}" alt="example1"/>
            <p id="details-title"> {{ fruit.name }}</p>
            <div id="info-wrapper">
                <div id="details-description">
                    <p>
                        {{ fruit.description }}
                    </p>
                    <p id="nutrition">Nutrition</p>
                    <p id="details-nutrition">
                        {% if fruit.nutrition %}
                            {{ fruit.nutrition }}
                        {% endif %}
                    </p>
                </div>

                <div id="action-buttons">
                    <a href="{% url 'fruitipedia:fruit_edit' fruit.id %}" id="edit-btn">Edit</a>
                    <a href="{% url 'fruitipedia:fruit_delete' fruit.id %}" id="delete-btn">Delete</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

Python/WebBasics/exam/templates/details-profile.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <section id="details">
        <div id="details-wrapper">
            <h2>Profile Details</h2>
            {% if profile.image_url %}
                <img id="details-img" src="{{ profile.image_url }}"
                alt="profile img"/>
            {% else %}
                <img id="details-img" src="/static/images/default.jpg" alt="profile img"/>
            {% endif %}

            <p id="details-title">{{ profile.first_name }} {{ profile.last_name }}</p>

            <div id="info-wrapper">
                <div id="details-description">
                    <p>
                        {{ profile.email }}
                    </p>
                    <p>
                        Age: {{ profile.age }}
                    </p>
                    <p id="nutrition">Posts: {{ fruits|length }}</p>

                </div>

                <div id="action-buttons">
                    <a href="{% url 'fruitipedia:profile_edit' %}" id="edit-btn">Edit</a>
                    <a href="{% url 'fruitipedia:profile_delete' %}" id="delete-btn">Delete</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

Python/WebBasics/exam/templates/edit-fruit.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <section id="edit">
        <div class="form">
            <h2>Edit Fruit</h2>
            <form class="edit-form"  method="POST">
                {{ form }}
                {% csrf_token %}
                <button type="submit">Edit</button>
            </form>
        </div>
    </section>
{% endblock %}

Python/WebBasics/exam/templates/edit-profile.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <section id="register">
        <div class="form">
            <h2>Edit Profile</h2>
            <form class="register-form"  method="POST">
                {{ form }}
                <button type="submit">Edit</button>
                {% csrf_token %}
            </form>
        </div>
    </section>
{% endblock %}

Python/WebBasics/exam/templates/index.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <section id="home">
      <h1>Learn more about your favorite fruits</h1>
      <img
        src="/static/images/pexels-pixabay-161559-dImkWBDHz-transformed (1).png"
        alt="home"
      />

    </section>
{% endblock %}