Python/WebBasics/exam_prep_01/exam_prep_01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("myplant.urls")),
]

Python/WebBasics/exam_prep_01/myplant/urls.py
from django.urls import path, include
from . import views

app_name = "myplant"

urlpatterns = [
    path("", views.home, name="home"),
    path("catalogue/", views.catalogue, name="catalogue"),
    path(
        "profile/",
        include(
            [
                path("create/", views.profile_create, name="profile_create"),
                path(
                    "details/", views.profile_details, name="profile_details"
                ),
                path("edit/", views.profile_edit, name="profile_edit"),
                path("delete/", views.profile_delete, name="profile_delete"),
            ]
        ),
    ),
    path("create/", views.plant_create, name="plant_create"),
    path("details/<int:plant_id>", views.plant_details, name="plant_details"),
    path("edit/<int:plant_id>", views.plant_edit, name="plant_edit"),
    path("delete/<int:plant_id>", views.plant_delete, name="plant_delete"),
]

Python/WebBasics/exam_prep_01/myplant/models.py
from django.db import models
from django.core.validators import RegexValidator

start_with_capital = RegexValidator(
    "^[A-Z].*", "Your name must start with a capital letter!"
)
min_two_letters = RegexValidator("^.{2,}$")
only_letters = RegexValidator(
    "^[A-Za-z]+$", "Plant name should contain only letters!"
)


class Profile(models.Model):
    username = models.CharField(
        verbose_name="Username",
        max_length=10,
        blank=False,
        unique=True,
        validators=[min_two_letters],
    )
    first_name = models.CharField(
        verbose_name="First name",
        max_length=20,
        blank=False,
        validators=[start_with_capital],
    )
    last_name = models.CharField(
        verbose_name="Last Name",
        max_length=20,
        blank=False,
        validators=[start_with_capital],
    )
    profile_picture = models.URLField("Profile Picture", null=True, blank=True)


TYPE = (
    ("Outdoor Plants", "Outdoor Plants"),
    ("Indoor Plants", "Indoor Plants"),
)


class Plant(models.Model):
    plant_type = models.CharField(
        verbose_name="Plant Type", max_length=14, blank=False, choices=TYPE,
    )
    name = models.CharField(
        verbose_name="Name",
        max_length=20,
        blank=False,
        validators=[min_two_letters, only_letters],
    )
    image_url = models.URLField(verbose_name="Image Url")
    description = models.TextField(verbose_name="Description")
    price = models.FloatField(verbose_name="Price")

Python/WebBasics/exam_prep_01/myplant/forms.py
from .models import Profile, Plant
from django import forms


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["username", "first_name", "last_name"]

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["username", "first_name", "last_name", "profile_picture"]
class PlantForm(forms.ModelForm):
    class Meta:
        model = Plant
        fields = "__all__"


class DeletePlantForm(PlantForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for (_, field) in self.fields.items():
            field.widget.attrs["disabled"] = "disabled"
            field.widget.attrs["readonly"] = "readonly"

Python/WebBasics/exam_prep_01/myplant/views.py
from django.shortcuts import render
from . import forms, models
from django.shortcuts import redirect


def home(request):
    profile = models.Profile.objects.first()
    return render(request, "home-page.html", {"profile": profile})


def catalogue(request):
    plants = models.Plant.objects.all()
    profile = models.Profile.objects.first()
    return render(
        request, "catalogue.html", {"plants": plants, "profile": profile}
    )


def profile_create(request):
    if request.method == "POST":
        form = forms.ProfileForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("myplant:catalogue")
    else:
        form = forms.ProfileForm()
        return render(request, "create-profile.html", {"form": form})


def profile_details(request):
    profile = models.Profile.objects.first()
    plants = models.Plant.objects.all()
    return render(
        request, "profile-details.html", {"profile": profile, "plants": plants}
    )


def profile_edit(request):
    profile = models.Profile.objects.first()

    if request.method == "POST":
        form = forms.ProfileEditForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect("myplant:profile_details")
        else:
            return render(
                request,
                "edit-profile.html",
                {"profile": profile, "form": form},
            )

    else:
        form = forms.ProfileEditForm(initial=profile.__dict__)

        return render(
            request, "edit-profile.html", {"profile": profile, "form": form}
        )


def profile_delete(request):
    profile = models.Profile.objects.first()
    plants = models.Plant.objects.all()

    if request.method == "POST":
        profile.delete()
        plants.delete()
        return redirect("myplant:home")

    else:
        return render(request, "delete-profile.html", {"profile": profile})


def plant_create(request):
    if request.method == "POST":
        form = forms.PlantForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("myplant:catalogue")
    else:
        form = forms.PlantForm()
        profile = models.Profile.objects.first()
        return render(
            request, "create-plant.html", {"profile": profile, "form": form}
        )


def plant_details(request, plant_id):
    profile = models.Profile.objects.first()
    plant = models.Plant.objects.get(id=plant_id)
    return render(
        request, "plant-details.html", {"profile": profile, "plant": plant}
    )


def plant_edit(request, plant_id):
    plant = models.Plant.objects.get(id=plant_id)
    if request.method == "POST":
        form = forms.PlantForm(request.POST, instance=plant)
        if form.is_valid():
            form.save()
            return redirect("myplant:catalogue")
        else:
            return render(
                request, "edit-plant.html", {"profile": profile, "form": form}
            )

    else:
        form = forms.PlantForm(initial=plant.__dict__)
        profile = models.Profile.objects.first()
        return render(
            request, "edit-plant.html", {"profile": profile, "form": form}
        )


def plant_delete(request, plant_id):
    plant = models.Plant.objects.get(id=plant_id)
    profile = models.Profile.objects.first()

    if request.method == "GET":
        form = forms.DeletePlantForm(initial=plant.__dict__)
        profile = models.Profile.objects.first()
        return render(
            request, "delete-plant.html", {"profile": profile, "form": form}
        )
    else:
        plant.delete()
        return redirect("myplant:catalogue")

Python/WebBasics/exam_prep_01/templates/catalogue.html
{% extends "./core/base.html" %}
{% load static %}

{% block content %}

{% if plants %}
    <section id="catalogue">

        {% for plant in plants %}
            <div class="plant-card">
                <div class="image-wrap">
                    <img src="{{ plant.image_url}}"
                        alt="{{ plant.type }}">
                </div>
                <h3>{{plant.name}}</h3>
                <h1>{{plant.description|truncatechars:20}}</h1>
                <div class="details-buttons">
                    <a href="{% url 'myplant:plant_details' plant.id %}" class="details-btn">Details</a>
                </div>
            </div>
        {% endfor %}
    </section>
{% else %}
    <p class="no-articles">No plants yet</p>
{% endif %}

{% endblock %}

Python/WebBasics/exam_prep_01/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyPlantApp</title>

    <link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}">

    {% block htmlhead %}
    {% endblock htmlhead %}
  </head>
  <body>
    <div id="box">
      {% include "./header.html" with static=static %}

      <main>
          {% block content %} {% endblock %} 
      </main>

      {% include "./footer.html" with static=static %}
    </div>
  </body>
</html>

Python/WebBasics/exam_prep_01/templates/core/footer.html
{% load static %} 

{% block content %}

<footer>
    &copy;SoftUni Team 2022. All rights reserved.
</footer>

{% endblock %}

Python/WebBasics/exam_prep_01/templates/core/header.html
{% load static %} 

{% block content %}

<header>
	<h1>
		<a class="index-navigation" href="{% url 'myplant:home' %}">MyPlants</a>
	</h1>
	<nav>
		{% if profile %}
			<a href="{% url 'myplant:catalogue' %}">Catalogue</a>
			<a href="{% url 'myplant:plant_create' %}">Create Plant</a>
			<a href="{% url 'myplant:profile_details' %}">Profile</a>
		{% else %}
			<a href="{% url 'myplant:profile_create' %}">Create Profile</a>
		{% endif %}
	</nav>
</header>

{% endblock %}

Python/WebBasics/exam_prep_01/templates/create-plant.html
{% extends "./core/base.html" %}
{% load static %}

{% block content %}

<section id="create-page" class="auth">
    <form id="create" method="POST">
        <div class="container">
            <h1 class="form-create-headline">Create Plant</h1>

            {{ form }}
            {% csrf_token %}

            <input class="btn" type="submit" value="Create Plant">

        </div>
    </form>
</section>

{% endblock %}

Python/WebBasics/exam_prep_01/templates/create-profile.html
{% extends "./core/base.html" %}
{% load static %}

{% block content %}

<section id="register-page" class="content auth">
    <form id="register" method="POST">
        {{ form }}
        <input class="btn submit" type="submit" value="Create Profile">
        {% csrf_token %}
    </form>
</section>

{% endblock %}

Python/WebBasics/exam_prep_01/templates/delete-plant.html
{% extends "./core/base.html" %}
{% load static %}

{% block content %}

<section id="delete-page" class="auth">

    <form id="delete" method="POST">
        <div class="container">
            <h1>Delete Plant</h1>

            {{ form }}
            {% csrf_token %}

            <input class="btn submit" type="submit" value="Delete Plant">

        </div>
    </form>
</section>

{% endblock %}

Python/WebBasics/exam_prep_01/templates/delete-profile.html
{% extends "./core/base.html" %}
{% load static %}

{% block content %}

<section id="create-page" class="auth">

  <div class="container">
    <h1>Are you sure you want to delete your profile?</h1>
    <form id='delete' method="POST">
        <input class="btn submit" type="submit" value="Yes">
        {% csrf_token %}
    </form>
  </div>
</section>

{% endblock %}

Python/WebBasics/exam_prep_01/templates/edit-plant.html
{% extends "./core/base.html" %}
{% load static %}

{% block content %}

<section id="create-page" class="auth">

    <form id="create" method="POST">
        <div class="container">
            <h1>Edit Plant</h1>

            {{ form }}
            {% csrf_token %}

            <input class="btn submit" type="submit" value="Edit Plant">

        </div>
    </form>
</section>

{% endblock %}

Python/WebBasics/exam_prep_01/templates/edit-profile.html
{% extends "./core/base.html" %}
{% load static %}

{% block content %}

<section id="register-page" class="content auth">

    <form id="register" method="POST">
        <div class="container">
            <h1>Edit Profile</h1>

            {{ form }}
            {% csrf_token %}

            <input class="btn" type="submit" value="Edit Profile">

        </div>
    </form>
</section>

{% endblock %}

Python/WebBasics/exam_prep_01/templates/home-page.html
{% extends "./core/base.html" %}
{% load static %}

{% block content %}

    <section id="index-headline">

        <div class="index-message">
            <h2>When there is plant</h2>
            <h3>there is live</h3>
            <h4>Join us now!</h4>
        </div>

    </section>

{% endblock %}

Python/WebBasics/exam_prep_01/templates/plant-details.html
{% extends "./core/base.html" %}
{% load static %}

{% block content %}

<section id="plant-details">
    <h1>Plant Details</h1>
    <div class="info-section">
        <div class="plant-header">
            <!-- plant image -->
            <img class="plant-img"
                 src="{{ plant.image_url}}"
                 alt='plant image'/>
            <!-- plant type -->
            <h1>{{ plant.type }}</h1>
            <!-- plant name -->
            <p><span class="description-plant">{{plant.name}}</span></p>
            <!-- plant price -->
            <p><span class="description-plant">Price: {{ plant.price|floatformat:2}}</span></p>
            <!-- plant description -->
            <p><span class="description-plant">{{plant.description}}</span></p>
        </div>

        <!-- Edit/Delete buttons -->
        <div class="buttons">
            <a href="{% url 'myplant:plant_edit' plant.id %}" class="edit-button">Edit</a>
            <a href="{% url 'myplant:plant_delete' plant.id %}" class="delete-button">Delete</a>
        </div>
    </div>
</section>

{% endblock %}

Python/WebBasics/exam_prep_01/templates/profile-details.html
{% extends "./core/base.html" %}
{% load static %}

{% block content %}

<section id="plant-details">
    <h1>Profile Details</h1>
    <div class="info-section">
        <div class="plant-header">
            {% if profile.profile_picture %}
                <img class="plant-img" src="{{ profile.profile_picture }}" alt='profile-image'/>
            {% else %}
                <img class="plant-img" src="/static/images/default.jpg" alt='profile-image'/>
            {% endif %}

            <h1>{{ profile.first_name}} {{ profile.last_name }}</h1>

            <p class="description">Username: {{ profile.username }}</p>

            <p class="description">Total stars:</p>

            {% if plants|length == 1 %}
                <img class="star-img" src="/static/images/star3.png" alt='profile-image'/>
            {% elif plants|length == 2 %}
                <img class="star-img" src="/static/images/star3.png" alt='profile-image'/>
                <img class="star-img" src="/static/images/star3.png" alt='profile-image'/>
            {% elif plants|length >= 3 %}
                <img class="star-img" src="/static/images/star3.png" alt='profile-image'/>
                <img class="star-img" src="/static/images/star3.png" alt='profile-image'/>
                <img class="star-img" src="/static/images/star3.png" alt='profile-image'/>
            {% else %}
                <p class="description">Total stars: 0</p>
            {% endif %}

            <div class="buttons">
                <a href="{% url 'myplant:profile_edit' %}" class="edit-button">Edit</a>
                <a href="{% url 'myplant:profile_delete' %}" class="delete-button">Delete</a>
            </div>
        </div>
    </div>
</section>

{% endblock %}